export const PROMPTS = [
  "Cat wearing sunglasses",
  "Rocket powered skateboard",
  "Banana pirate",
  "Robot making pancakes",
  "Shark on a bicycle",
  "Dinosaur at a job interview",
  "Coffee cup with tiny legs",
  "Penguin DJ",
  "Alien tourist in San Jose",
  "Hotdog doing yoga",
  "Octopus chef",
  "Wizard at the beach",
  "Taco spaceship",
  "Hamster weightlifter",
  "Cloud with a mustache",
  "Snail race champion",
  "Giraffe in a tiny car",
  "Ninja pineapple",
  "Sleepy moon with slippers",
  "Corgi astronaut",
  "Toaster superhero",
  "Sushi rollercoaster",
  "Karaoke dragon",
  "Skateboarding ramen",
  "Unicorn programmer",
  "Broccoli villain",
  "UFO at In-N-Out",
  "Koala barista",
  "Spaghetti lasso",
  "Duck detective",
];
